---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-private
  template:
    metadata:
      labels:
        app: website-private
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: website
        image: nginx:stable-alpine
        volumeMounts:
        - name: index-html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
      volumes:
        - name: index-html
          configMap:
            name: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: website-private
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: website-private
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: website-private-ingress
  annotations:
    kubernetes.io/ingress.class: ingress-private
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: website-private
          servicePort: 80
        path: /
