apiVersion: v1
kind: Pod
metadata:
  name: tls-test-pod
spec:
  containers:
  - name: tls-test
    image: ubuntu:latest
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    volumeMounts:
      - name: tlstest
        mountPath: /tls
  volumes:
  - name: tlstest
    csi:
      driver: csi.cert-manager.io
      volumeAttributes:
        csi.cert-manager.io/issuer-name: ca-issuer
        csi.cert-manager.io/dns-names: tls-test.sandbox.svc.cluster.local
        csi.cert-manager.io/uri-sans: spiffe://tls-test.sandbox.cluster.local